### PR TITLE
Some cleanups to allow more than 4 channels to be decoded

### PR DESCRIPTION
**Pull request by ckuethe**
With this patchset, I'm able to run acarsdec on a single core 1GHz Cortex-A8 (VPFv3 and NEON) decoding 8 channels using less than 60% CPU.

### CODE REVIEW

**Comment by zsssapp** [comment]
Do you mean you can run acarsdec with an airspy dongle decoding 8 CHs? right?

**Comment by ckuethe** [comment]
The arm board I'm running can't supply enough power on the USB port to run the airspy, but I can decode 8 channels from an RTL. The airspy driver already had 8 channel support.

**Comment by zsssapp** [comment]
Thx. I am receiving 3 channels running airspy mini dongle on a raspberry pi 2 board. Although it works, the decoding result is not acceptable, trying to figure out how to improve it.

**Comment by ckuethe** [comment]
Check your analog side. Are you using a good antenna? Is your feed line in good conditions? Is there lots of RF interference? Is your gain set properly? Are you using the right PPM correction? Do you have good line of sight? Are there even many aircraft around you to listen to? Can you reproduce the poor reception near an airport?

`acarsdec -p 22 -g 1000 -r 0 131.55 130.025 129.125 130.425 130.45 131.125 130.575 131.475` works for me

**Comment by zsssapp** [comment]
rtl is now receiving much much better than airspy mini with the same antenna and coax. May be is the gain settings.
________________________________
发件人: ckuethe<mailto:notifications@github.com>
发送时间: ‎2016/‎11/‎5 3:11
收件人: TLeconte/acarsdec<mailto:acarsdec@noreply.github.com>
抄送: zsssapp<mailto:lavaspan@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [TLeconte/acarsdec] Some cleanups to allow more than 4 channels to be decoded (#1)


Check your analog side. Are you using a good antenna? Is your feed line in good conditions? Is there lots of RF interference? Is your gain set properly? Are you using the right PPM correction? Do you have good line of sight? Are there even many aircraft around you to listen to? Can you reproduce the poor reception near an airport?

acarsdec -p 22 -g 1000 -r 0 131.55 130.025 129.125 130.425 130.45 131.125 130.575 131.475 works for me

**Comment by ckuethe** [comment]
I'm going to close this PR and will resend some similar changes against 3.4

**Pull request closed without merging**
